GadgetsOnline/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GadgetsOnline.Models;
using GadgetsOnline.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace GadgetsOnline.Controllers
{
    public class CheckoutController : Controller
    {
        OrderProcessing orderProcessing;
        private OrderProcessing GetOrderProcess()
        {
            if (this.orderProcessing == null)
            {
                this.orderProcessing = new OrderProcessing();
            }

            return this.orderProcessing;
        }

        // GET: Checkout
        public ActionResult Index()
        {
            return View();
        }

        // GET: Checkout
        public ActionResult AddressAndPayment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            /* Added by CTA: This updated method might require the parameters to be re-organized */
            TryUpdateModelAsync(order);
            try
            {
                order.Username = "Anonymous";
                order.OrderDate = DateTime.Now;
                bool result = GetOrderProcess().ProcessOrder(order, this.HttpContext);
                return RedirectToAction("Complete", new
                {
                id = order.OrderId
                }

                );
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }

        public ActionResult Complete(int id)
        {
            return View(id);
        }
    }
}

GadgetsOnline/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GadgetsOnline.Models;
using GadgetsOnline.Services;
using GadgetsOnline.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace GadgetsOnline.Controllers
{
    public class ShoppingCartController : Controller
    {
        Inventory inventory;
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel{CartItems = cart.GetCartItems(), CartTotal = cart.GetTotal()};
            // Return the view
            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(id);
            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            int itemCount = cart.RemoveFromCart(id);
            inventory = new Inventory();
            var productName = inventory.GetProductNameById(id);
            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel{Message = HtmlEncoder.Default.Encode(productName) + " has been removed from your shopping cart.", CartTotal = cart.GetTotal(), CartCount = cart.GetCount(), ItemCount = itemCount, DeleteId = id};
            return RedirectToAction("Index");
        }
    }
}

GadgetsOnline/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GadgetsOnline.Models;
using GadgetsOnline.Services;
using Microsoft.AspNetCore.Mvc;

namespace GadgetsOnline.Controllers
{
    public class StoreController : Controller
    {
        Inventory inventory;
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Browse(string category)
        {
            inventory = new Inventory();
            var productModel = inventory.GetAllProductsInCategory(category);
            return View(productModel);
        }

        public ActionResult Details(int id)
        {
            inventory = new Inventory();
            var album = inventory.GetProductById(id);
            return View(album);
        }
    }
}

GadgetsOnline/Views/ShoppingCart/Index.cshtml
@model GadgetsOnline.ViewModel.ShoppingCartViewModel
@{ ViewBag.Title = "Shopping Cart"; }

<script src="~/Scripts/jquery-3.5.1.min.js" type="text/javascript"></script>
<script type="text/javascript">$(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");

            if (recordToDelete != '') {

                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }

                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });

    });


    function handleUpdate() {
        // Load and deserialize the returned JSON data
        var json = context.get_data();
        var data = Sys.Serialization.JavaScriptSerializer.deserialize(json);

        // Update the page elements
        if (data.ItemCount == 0) {
            $('#row-' + data.DeleteId).fadeOut('slow');
        } else {
            $('#item-count-' + data.DeleteId).text(data.ItemCount);
        }

        $('#cart-total').text(data.CartTotal);
        $('#update-message').text(data.Message);
        $('#cart-status').text('Cart (' + data.CartCount + ')');
    }</script>
<h3>
    <em>Review</em> your cart:
</h3>
<p class="button">
    @Html.ActionLink("Checkout >>", "AddressAndPayment", "Checkout")
</p>
<div id="update-message">
</div>
<table>
    <tr>
        <th>
            Pizza
        </th>
        <th>
            Price (each)
        </th>
        <th>
            Quantity
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.CartItems)
    {
<tr id="row-@item.RecordId">
    <td>
        @Html.ActionLink(item.Product.Name, "Details", "Store", new { id = item.ProductId }, null)
    </td>
    <td>
        @item.Product.Price
    </td>
    <td id="item-count-@item.RecordId">
        @item.Count
    </td>
    <td>
        @Html.ActionLink("Remove from cart", "RemoveFromCart", "ShoppingCart", new { id = item.ProductId }, null)
        @*<a href="#" class="RemoveLink" data-id="@item.RecordId">Remove from cart</a>*@
    </td>
</tr>
}
    <tr>
        <td>
            Total
        </td>
        <td>
        </td>
        <td>
        </td>
        <td id="cart-total">
            @Model.CartTotal
        </td>
    </tr>
</table>