GadgetsOnline/Components/CategoryMenuViewComponent.cs
using GadgetsOnline.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GadgetsOnline.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        Inventory inventory;

        public async Task<IViewComponentResult> InvokeAsync()
        {
            inventory = new Inventory();
            var categories = inventory.GetAllCategories();
            return View(categories);
        }
    }
}

GadgetsOnline/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GadgetsOnline.Models;
using GadgetsOnline.Services;
using Microsoft.AspNetCore.Mvc;

namespace GadgetsOnline.Controllers
{
    public class StoreController : Controller
    {
        Inventory inventory;
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Browse(string category)
        {
            inventory = new Inventory();
            var productModel = inventory.GetAllProductsInCategory(category);
            return View(productModel);
        }

        public ActionResult Details(int id)
        {
            inventory = new Inventory();
            var album = inventory.GetProductById(id);
            return View(album);
        }
    }
}

GadgetsOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet"
          type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-3.6.0.min.js")"
            type="text/javascript"></script>
</head>
<body>
    <div id="header" style="margin-top:10px">

        <h1 class="font-italic"><a href="/">
            Welcome to Global Gadgets Online!
             </a>
        </h1>

        <ul id="navlist">
            @if (User.Identity.IsAuthenticated)
            {
<li><a>Welcome @User.Identity.Name</a></li>}
 <li><a href="@Url.Content("~/Home")" id="current">Home</a></li>
            <li><a href="@Url.Content("~/ShoppingCart")">ShoppingCart</a></li>            
        </ul>
    </div>

@*@{Html.RenderAction("CategoryMenu", "Store");}*@ @*OLD*@
@await Component.InvokeAsync("CategoryMenu")


    <div id="main">
        @RenderBody()
    </div>

    <div id="footer">
        <a href="https://aws.amazon.com/developer/language/net/"> AWS &#10084;&#65039;  ASP.NET </a>
    </div>
</body>
</html>